# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Smart BMS Utility' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart BMS Utility
  pod 'MBCircularProgressBar'
  pod 'SwiftSocket'
end
